
window.CRMUI=(function(){let sb=null,cfg={getOrgId:()=>'',
supabaseUrl:'',anonKey:''};
function h(t,a={},c=[]){const e=document.createElement(t);for(const[k,v]of Object.entries(a)){if(k==='class')e.className=v;else if(k.startsWith('on')&&typeof v==='function')e.addEventListener(k.slice(2),v);else e.setAttribute(k,v)}for(const n of(Array.isArray(c)?c:[c])){if(n==null)continue;e.appendChild(typeof n==='string'?document.createTextNode(n):n)}return e}
function fmt(ts=new Date()){const p=n=>String(n).padStart(2,'0');return ts.getFullYear()+"-"+p(ts.getMonth()+1)+"-"+p(ts.getDate())+"T"+p(ts.getHours())+":"+p(ts.getMinutes())}
function modal(){const r=h('div',{class:'crm-modal',id:'crm-modal'}),card=h('div',{class:'crm-card'}),head=h('div',{class:'crm-h'},[h('div',{},[h('strong',{},'Toevoegen / Bewerken')]),h('button',{class:'btn ghost',onClick:()=>r.style.display='none'},'Sluiten')]),body=h('div',{class:'crm-body'}),tabs=h('div',{class:'crm-tabs'}),content=h('div',{id:'crm-content'}),defs=[{key:'interactie',label:'Interactie'},{key:'traject',label:'Traject'},{key:'attribuut',label:'Attribuut'},{key:'klant',label:'Klantgegevens'}];let a='interactie';function rt(){tabs.innerHTML='';for(const t of defs){const b=h('button',{class:'crm-tab'+(t.key===a?' active':''),onClick:()=>{a=t.key;rt();rc()}},t.label);tabs.appendChild(b)}}function rc(){content.innerHTML='';if(a==='interactie')content.appendChild(vI());if(a==='traject')content.appendChild(vT());if(a==='attribuut')content.appendChild(vA());if(a==='klant')content.appendChild(vK())}body.appendChild(tabs);body.appendChild(content);card.appendChild(head);card.appendChild(body);r.appendChild(card);document.body.appendChild(r);rt();rc();return{open:()=>r.style.display='flex'}}
function vI(){const orgId=cfg.getOrgId();return h('div',{},[h('div',{class:'crm-grid'},[f('Datum/tijd',h('input',{type:'datetime-local',id:'ci_time',value:fmt()})),f('Type',sel('ci_kind',['meeting','call','email','bezoek','actie','overig'])),f('Onderwerp',h('input',{id:'ci_subject',placeholder:'bv. Kennismaking'})),f('Kanaal',sel('ci_channel',['on-site','online','phone','mail'])),f('Notitie',h('textarea',{id:'ci_notes',rows:'4',placeholder:'Korte notitie...'}),true)]),acts(async()=>{const occurred_at=new Date(document.getElementById('ci_time').value||new Date());const {error}=await sb.from('club_interactions').insert({org_id:orgId,occurred_at:occurred_at.toISOString(),kind:val('ci_kind'),subject:val('ci_subject')||null,notes:(document.getElementById('ci_notes').value||'')||null,channel:val('ci_channel')||null}); ok(error,'Interactie opgeslagen.')])])}
function vT(){const orgId=cfg.getOrgId();return h('div',{},[h('div',{class:'crm-grid'},[f('Titel',h('input',{id:'tr_title',placeholder:'bv. Vrijwilligersbeleid'})),f('Status',sel('tr_status',['open','lopend','on-hold','afgerond','geannuleerd'])),f('Startdatum',h('input',{type:'date',id:'tr_start',value:(new Date()).toISOString().slice(0,10)})),f('Notitie (event)',h('input',{id:'tse_note',placeholder:'optioneel'}))]),acts(async()=>{const ins=await sb.from('trajecten').insert({org_id:orgId,titel:val('tr_title'),status:val('tr_status'),start_datum:document.getElementById('tr_start').value}).select('id,status').single();if(ins.error)throw ins.error;await sb.from('traject_status_events').insert({traject_id:ins.data.id,old_status:null,new_status:ins.data.status,note:val('tse_note')||null}); ok(null,'Traject opgeslagen.')])])}
function vA(){const orgId=cfg.getOrgId();return h('div',{},[h('div',{class:'crm-grid'},[f('Attribuut',sel('at_key',['nieuwsbrief_ontvangen','sociaal_veilig','privacyverklaring','vwc_aanwezig'])),f('Waarde',sel('at_val',[['1','Ja'],['0','Nee']])),f('Ingangsdatum',h('input',{type:'date',id:'at_from',value:(new Date()).toISOString().slice(0,10)}))]),acts(async()=>{const {error}=await sb.from('organization_attribute_facts').insert({org_id:orgId,attr_key:val('at_key'),value:parseInt(val('at_val'),10),valid_from:document.getElementById('at_from').value}); ok(error,'Attribuut vastgelegd.')])])}
function vK(){const orgId=cfg.getOrgId();const w=h('div',{},[h('div',{class:'crm-grid'},[f('Naam',h('input',{id:'org_name'})),f('Sport',h('input',{id:'org_sport'})),f('Gemeente',h('input',{id:'org_muni'})),f('Plaats',h('input',{id:'org_city'})),f('Postcode',h('input',{id:'org_post'})),f('Eigen kantine',sel('org_kant',[['true','Ja'],['false','Nee']]))]),acts(async()=>{const u=await sb.from('organizations').update({name:val('org_name')||null,sport:val('org_sport')||null,municipality:val('org_muni')||null,city:val('org_city')||null,postal_code:val('org_post')||null,has_canteen:val('org_kant')==='true',updated_by:'crm-vanilla-ui'}).eq('id_code',orgId); ok(u.error,'Gegevens bijgewerkt.')})]);(async()=>{const {data}=await sb.from('organizations').select('name,sport,municipality,city,postal_code,has_canteen').eq('id_code',orgId).single(); if(data){sv('org_name',data.name||'');sv('org_sport',data.sport||'');sv('org_muni',data.municipality||'');sv('org_city',data.city||'');sv('org_post',data.postal_code||'');sv('org_kant',String(!!data.has_canteen))}})();return w}
function f(l,c,full=false){const r=h('div',{class:'crm-row'});r.appendChild(h('label',{},l));r.appendChild(c);if(full)r.style.gridColumn='1 / -1';return r}
function sel(id,items){const s=h('select',{id});for(const it of items){if(Array.isArray(it))s.appendChild(h('option',{value:it[0]},it[1]));else s.appendChild(h('option',{value:it},it))}return s}
function val(id){return (document.getElementById(id)||{}).value}
function sv(id,v){const el=document.getElementById(id); if(el) el.value=v}
function acts(onSave){return h('div',{class:'crm-actions'},[h('button',{class:'btn ghost',onClick:()=>document.getElementById('crm-modal').style.display='none'},'Annuleren'),h('button',{class:'btn',onClick:async()=>{try{await onSave(); toast('✅ Opgeslagen')}catch(e){console.error(e);toast('❌ Fout: '+(e.message||e))}}},'Opslaan')])}
let tt=null;function toast(m){let t=document.getElementById('crm-toast'); if(!t){t=h('div',{id:'crm-toast',style:'position:fixed;bottom:16px;left:50%;transform:translateX(-50%);background:#0f172a;color:#fff;padding:10px 14px;border-radius:10px;z-index:10000;'});document.body.appendChild(t)}t.textContent=m;t.style.display='block';clearTimeout(tt);tt=setTimeout(()=>t.style.display='none',2400)}
return{init:({supabaseUrl,anonKey,getOrgId})=>{if(!window.supabase)throw new Error('Supabase JS niet gevonden. Voeg de CDN script-tag toe.'); cfg.supabaseUrl=supabaseUrl; cfg.anonKey=anonKey; cfg.getOrgId=getOrgId; sb=window.supabase.createClient(supabaseUrl,anonKey,{auth:{persistSession:false}}); if(!document.getElementById('crm-modal')) modal()},
attach:(selr)=>{const btn=document.querySelector(selr); if(!btn) return; btn.addEventListener('click',()=>{const m=document.getElementById('crm-modal'); if(m) m.remove(); const {open}=modal(); open()})}}
})();
